#!/usr/bin/awk -f

BEGIN {
	start = 0
	count = 200
	print "import unittest"
	print ""
	print "from TestUtils import TestParser"
	print ""
	print ""
	print "class ParserSuite(unittest.TestCase):"
}

/^##/ {
	start = 1
	next
}

$0 ~ /^class/ {
	next
}

start == 1 && $0 ~ /^ {8}self\.check_parser/ {
	sub("check_parser", "assertTrue(TestParser.checkParser")
	sub(/\)$/, ", " count++ "))")
}

start == 1 {
	print $0
}
