#!/bin/sh

unzip -q src/ass1.zip 'initial/**'

cp dist/BKIT.g4 initial/src/main/bkit/parser/BKIT.g4
cp dist/ASTGenSuite.py initial/src/test/ASTGenSuite.py
cp dist/ASTGeneration.py initial/src/main/bkit/astgen/ASTGeneration.py

cd initial/src/ || exit

ANTLR_JAR="$OLDPWD"/antlr-4.8-complete.jar python run.py gen
python run.py test ASTGenSuite

cd "$OLDPWD" || exit
rm -r initial/
